os: linux
dist: xenial
language: python
addons:
  apt:
    packages:
      - unixodbc-dev
python:
  - 3.9
install:
  - pip install -r requirements.txt
script:
  - pyinstaller main.py --name SoFIFA_to_PES5_WE9_LE --noconsole
after_success:
  - cp -R mdb_template/ dist/SoFIFA?to?PES5_WE9_LE/mdb_template/
